default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ecommerce_app
  username: puneet
  host: localhost
  password: puneet

test: &test
  <<: *default
  database: ecommerce_app_test
  username: puneet
  password: puneet
  host: localhost

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: ecommerce_app_prod
  username: puneet
  password: puneet
  host: localhost
  port: 5432